### ISSUE TITLE
Accounts Get geeft fout

### ISSUE THREAD

**Issue by stefbuenen** [FelixvL/klmBookingBE#22]
failed to lazily initialize a collection of role: yc.klm.booking.domain.Account.orders, could not initialize proxy - no Session (through reference chain: yc.klm.booking.domain.Account["orders"])

**Comment by rloman** [comment]
Wordt altijd een beetje gek van eager en lazy collections, jij ook ? :-(

**Comment by rloman** [comment]
Fixed

**Comment by rloman** [comment]
(will deploy later)
